### ISSUE TITLE
Scrollkey e10s compatiblity, checkboxes missing

### ISSUE THREAD

**Issue by rayman89** [Smile4ever/firefoxaddons#23] opened 2017-06-21 20:40 UTC
Is this addon compatible with e10s? The add-on reporter says it's but I've been getting inconsistent behavior when enabled. It sometimes doesn't work, sometimes av. pag/re pag works like vanilla firefox but other times works all properly.

BTW will this addon work with the firefox 57+ update that will only work with web extension addons?

**Comment by Smile4ever** [comment] 2017-06-21 20:41
Which addon are we talking about?

**Comment by rayman89** [comment] 2017-06-21 20:45
Scrollkey 1.1.0

**Comment by Smile4ever** [comment] 2017-06-21 20:50
Yes, it is already a WebExtension so it will be compatible when Firefox 57 comes out. Scrollkey 1.0 and up are compatible with e10s. Scrollkey 1.0+ requires Firefox 48 or up. If you have a recent Firefox version it should not disable Scrollkey.

**Comment by Smile4ever** [comment] 2017-06-21 20:52
If you can reproduce a specific problem I can look at it.

**Comment by rayman89** [comment] 2017-06-21 20:52
On firefox 55 check boxes for the options are missing. 

I've also like I said before been getting inconsistent behavior idk if it's de e10s enabled of the new firefox version. It sometimes doesn't work, sometimes av. pag/re pag works like vanilla firefox but other times works all properly.

**Comment by rayman89** [comment] 2017-06-21 20:55
EDIT: test it on this page  https://addons.mozilla.org/en-US/firefox/addon/scrollkey/  on firefox 55 x64 on windows with scroll amounts of 3 pixels and all checkboxes enabled but first one  (if you can get to see the boxes)

**Comment by Smile4ever** [comment] 2017-06-21 20:56
Checkboxes do not work because of a bug in Firefox Nightly and Firefox Beta. I have made a workaround for Translate Now, I will implement this for Scrollkey as well.

**Comment by rayman89** [comment] 2017-06-21 20:59
Great. Will that fix the issues with the scrolling as well?

**Comment by Smile4ever** [comment] 2017-06-21 21:00
WebExtensions do not support privileged sites like addons.mozilla.org. This is a limitation of Firefox for security reasons. I will add an explanation on the addons page.

**Comment by Smile4ever** [comment] 2017-06-21 21:03
No, but I will make clear where Scrollkey should work and in what cases it will be supported. Improved APIs in the future could make it possible to support addons.mozilla.org.

**Comment by rayman89** [comment] 2017-06-21 22:03
I tested on a clean profile and it worked as expected but on my profile some pages for example like youtube memecenter.com etc dont work. I disabled all addons but scrollkey and still does not work any idea of what could be the problem?

**Comment by Smile4ever** [comment] 2017-06-22 04:54
> I tested on a clean profile and it worked as expected but on my profile some pages for example like youtube memecenter.com etc dont work. I disabled all addons but scrollkey and still does not work any idea of what could be the problem?

If a text field is focused, Scrollkey will not work. Click on an empty white area, then Scrollkey should work.

If it still doesn't work, I suggest you rebuild your configuration (addons, bookmarks) in a new profile.

**Comment by Smile4ever** [comment] 2017-06-23 19:25
I added a disclaimer to the addons page. I am working on some small improvements for Scrollkey so it will take a bit longer.

**Comment by rayman89** [comment] 2017-06-23 19:44
I realized that the issue was that it got stuck on making the scroll only be horizontal so the addon is working but I cannot make it scroll vertically until the update allows me to change the options.

**Comment by Smile4ever** [comment] 2017-06-24 15:09
https://github.com/Smile4ever/firefoxaddons/commit/9dd61358c6bd93fd49867e664df3d9c2ce3a65c6 implements a workaround for the checkboxes not being visible in Firefox 55 and Firefox 56.

The fix is available in Scrollkey 2.0.0 which will soon be available on addons.mozilla.org.

**Comment by rayman89** [comment] 2017-06-25 16:47
The new version seems to work well. I tested many pages but idk why on this page it does not work. Is it the same as the AMO page?

warning there might be NSFW material on this page

http://www.jaidefinichon.com/

**Comment by Smile4ever** [comment] 2017-06-25 17:25
>The new version seems to work well.

Good to hear that.

> I tested many pages but idk why on this page it does not work. Is it the same as the AMO page?

It is unrelated. The issue you're facing is related to iframe handling I'm afraid. You can use this link instead: http://v2.jaidefinichon.com/

I've tried to implement iframe support in version 2, but it doesn't work always. I might change the iframe handling in the future to be more robuust (if feasible). Thanks for the testing URL.

I will close this issue now, but you can still comment if you want.

**Closed by Smile4ever** 2017-06-25 17:25 UTC
