### ISSUE TITLE
Scrollkey: Last update (1.0+) broke it

### ISSUE THREAD

**Issue by rayman89** [Smile4ever/firefoxaddons#13] opened 2017-01-09 06:31 UTC
Last update caused av pag and re pag to not work anymore same with horizontal scrolling. Only J and K work and alt + j/k shift + j/K doesnt work either. (yes I know you changed the preferences and yes I edited them there and press the button to save it and checked that they did save and also tested it on a new clean profile). BTW the spanish translation is pretty bad. Idk if it's automatic or what but if you want I can do the translation to spanish.

Firefox version 51 beta 12 x64
e10s disabled
tested on many sites like youtube, google, mozilla addons, no script forums, etc etc etc
neither version 1.0 nor 1.0.1 are working for me (j and k work avpag re pag shift/alt + j/k does not) 0.7 does work as intended.

**Comment by Smile4ever** [comment] 2017-01-09 07:32
Could you please try Firefox 53 (Nightly)?
What settings do you use?

**Comment by rayman89** [comment] 2017-01-16 22:46
I tried the default settings and small numbers like 1, 3, 4, 6, 10 etc. 
I tried it on firefox 53 x64 and it's the same. Av pag Re pag functionality is not affected by the mod alt/shift + j/K does not work. Horizontal scrolling does not work.  Only j/K functionality does work.

**Comment by rayman89** [comment] 2017-01-19 14:33
I tried the default settings and small numbers like 1, 3, 4, 6, 10 etc.
I tried it on firefox 53 x64 and it's the same. Av pag Re pag functionality is not affected by the mod alt/shift + j/K does not work. Horizontal scrolling does not work. Only j/K functionality does work.

I'm on windows 7 x64

**Comment by Smile4ever** [comment] 2017-01-19 17:30
I cannot reproduce this under Windows 7 x64, Windows 7 x86 or Linux. It's working perfectly fine for me.

Please try Scrollkey on another computer and report back to me. Thank you.

**Comment by rayman89** [comment] 2017-01-23 01:43
I asked my gf to test it on her pc and it's the exact same. Are you sure that the version you are using is the same as the one that is on the server?

**Comment by Smile4ever** [comment] 2017-01-23 06:57
Yes, I created a clean profile on Firefox 53 and I downloaded Scrollkey 1.0.1 from AMO. Scrollkey works perfectly here.

Can you make horizontal scrolling work on the J/K combination?

**Comment by rayman89** [comment] 2017-01-23 08:37
No only j/k work as intended the rest does not work at all.

**Comment by rayman89** [comment] 2017-01-27 01:38
Do you have the chance to test it on an other pc or firefox version? I tested it on my workplace with the same results.

**Comment by Smile4ever** [comment] 2017-01-27 12:40
Yes, I tested it on three computers:
* Manjaro Linux: no problems using Firefox 53
* Windows 7 x64: no problems using Firefox 51.0.1
* Windows 10 x64: no problems using Firefox 54.0a1

1) Did your girlfriend use a clean profile to test?
2) Did you use a clean profile to test at your workplace?
3) Open the browser console. -> Press the Scrollkey shortcuts on a page. -> Please attach any JavaScript info that appears in Browser Console (CTRL+SHIFT+J) to this bug report.

**Comment by Smile4ever** [comment] 2017-01-28 20:24
A friend tested this as well using Windows 10 and Firefox 51 and he had no issues at all.

**Comment by rayman89** [comment] 2017-01-28 22:28
All test were done on a clean profile with e10s disabled.

I did a bit more testing and with e10s ON, the side scroll works the only thing not working with or without e10s is the av pag and re pag buttons moving the amount specified they move the amount they always do without any addon. Ticking the option to move horizontally using av pag and re pag does not work either and makes "j" and "k" to move you horizontally instead of vertically.

This is the only error that appears that is JS but I think is not related with your add-on "SyntaxError: JSON.parse: expected double-quoted property name at line 1 column 46 of the JSON data[Learn More]" (GCTelemetry.jsm:194:16)

**Comment by Smile4ever** [comment] 2017-01-29 09:51
> "I did a bit more testing and with e10s ON, the side scroll works"

Nice to hear. I disabled e10s and tested it, but it still works then. I will be closing this bug, but you may still comment if you have any further information. 

> the only thing not working with or without e10s is the av pag and re pag buttons moving the amount specified they move the amount they always do without any addon.

AvPag (PageUp) and RePag (PageDown) were indeed broken since 1.0. These are fixed in Scrollkey 1.0.2. I landed scroll speed improvements for PageUp and PageDown in Scrollkey 1.0.2 as well: e506e84

Scrollkey 1.0.2 will soon be available at https://addons.mozilla.org/nl/firefox/addon/scrollkey/versions

> Ticking the option to move horizontally using av pag and re pag does not work either and makes "j" and "k" to move you horizontally instead of vertically.

That's by design, you CANNOT make PageUp/PageDown scroll horizontally. It was the same in Scrollkey 0.7.0.

> This is the only error that appears that is JS but I think is not related with your add-on "SyntaxError: JSON.parse: expected double-quoted property name at line 1 column 46 of the JSON data[Learn More]" (GCTelemetry.jsm:194:16)

Unrelated indeed.

**Closed by Smile4ever** 2017-01-29 09:51 UTC

**Comment by rayman89** [comment] 2017-01-29 15:34
Oh I never tried the first option for horizontal scrolling before but it's a bit confusing then if it's not for av pag and re pag (at least in the spanish translation) because it says "Utilice la tecla de acceso directo de arriba para el desplazamiento horizontal" which in english would be: Use the stated above key to move horizontally. And the stated above keys are Av Pag and Re pag.

Would be more clear if the horizontal scroll option was first and instead said "Usar las teclas de desplazamiento para movimiento horizontal" which in english would mean "Use the scroll keys to move horizontally"

**Comment by Smile4ever** [comment] 2017-01-29 18:14
>Oh I never tried the first option for horizontal scrolling before but it's a bit confusing then if it's not for av pag and re pag (at least in the spanish translation) because it says "Utilice la tecla de acceso directo de arriba para el desplazamiento horizontal" which in english would be: Use the stated above key to move horizontally. And the stated above keys are Av Pag and Re pag.

Not really. The settings are for j/k, not for PageUp/PageDown, that's just an extra checkbox. I might put PageUp/PageDown settings in a separate box in the future.

> Would be more clear if the horizontal scroll option was first

The PageDown/PageUp option is taking the value of j/k scroll, and the "horizontal scroll" checkbox is for that j/k scrolling. Having the horizontal scroll option first would make it clearer indeed. That's what I did for the Scrollkey development release just now, so you will see this in a future version.

> and instead said "Usar las teclas de desplazamiento para movimiento horizontal" which in english would mean "Use the scroll keys to move horizontally"

Won't be needed if I split out PageUp/PageDown settings in their own box.
